import { cardcontainer,cards, documentation ,images,figcaptions} from "./material-kit-react.js";
const CardZZ = {
    pcontainer:{
        position:'relative',
        alignItems:'center',
        alignContent:"space-around",
        marginLeft:'-24px',
        boxShadow: "inset 1em 0 rgba(228,23,106,1) ",
        color: "#425bf2",
        background:"#fbfbf8", 
        padding:'1rem',
        height:"auto",
        overflow:"auto",
        border:"2px solid #fff",
        ...cardcontainer,
    },
    images:{
        borderBottom:'2px solid grey',
        borderTopRightRadius:'5rem',borderTopLeftRadius:'5rem',
           height:'20rem',
           boxSizing:'border-box',
           ...images
    },
    socialMediaButton:{
        width:'50px',
        height:'50px',
        borderRadius:'28px',
        border:'1px solid white',
        marginLeft:'20px',
        
    },
    carts:{
        zIndex:'0',
        display: "flex",
        flexDirection:'column',
        alignItems: 'center',
        alignContent:'center',
        background :'transparent',
        position: "relative",
        marginLeft:'5px',
        height:'30rem',
        borderTopLeftRadius:'5rem',
        borderBottomRightRadius:'5rem',
        border:'2px solid #c2c2c2',
        color:'black',
        fontFamily:'forte',
        letterSpacing:'1px',
        fontSize:'26px',
        ...cards 
    },
    boxcontent:{
        display: 'flex',
        flexDirection:'column',
        position:'absolute',
        width:'100%',
        height:'100%',
        alignItems:'center',
        alignContent:'center',
        },
    content:{
        display: 'block',
        position:'absolute',
        width:'100%',
        height:'100%',
        borderTopLeftRadius:'4rem',
        boxShadow:'10px 0 50px rgba(0,0,0,0)',
        top:'0%',
        left:'0%',
        backdropFilter: 'drop-shadow(4px 4px 10px pink), blur(20px)',
        background:'rgba(228,23,106,1) ',
        clipPath:'circle(90px at 0 0 )',
        transition:'all 0.5s',
        cursor:'pointer',
        whiteSpace:'nowrap',
        textTransform:'uppercase',
        fontFamily:' Monaco, Consolas',
        fontSize:'32px',
        letterSpacing:'1px',
        //transform:'translate(-50%,-50%)',
        color:'white',
       "&:hover" :{
        clipPath:'circle(800px at 0 0 )',
       }
    },
   iconbutton:{
     position:'absolute',
     top:'0px',
     left:'0px',
     opacity:'1',
     transition:'all 0.3s',
     color:'#fff',
     transform:'rotate(-45deg)',
     fontFamily:' Monaco',
     fontSize:'32px',
     letterSpacing:'1px',
    },
    documentation:{
        ...documentation,
        alignItems:'center',
        display:'block',
        float:'left',
        marginTop:'25px',
        flexDirection:'column',
        textAlign: "left",
        position:'relative',
        width:'87%',
        padding:'5px',
        border:'1px solid #fff',
        boxShadow:'inset 0 0 1em #fb7287',
        cursor:'pointer',
        background:'#fff',
        color:'black',
        height:"auto",
    },
    footDocument:{
     width:'100%',
     display:'flex',
     
    },
    p:{
     textDecoration: "none",
     textAlign:'left',
    },
    figcaptions:{
        ...figcaptions,
       alignItems:'center',
       alignContent:'center',
       color:'grey',
       zIndex:'42' ,
       fontWeight:'bold',
       textDecoration:'uppercase',
       TextAlign:'center',
   }
};

export default CardZZ;